### ISSUE TITLE
Modified the Navigation bar in Pricing and features and Fixed the contact view

### ISSUE THREAD

**Issue by saiadityaviswanadham** [arpit456jain/CodingEasy#129]
The Navigation bar was modified such that users can navigate from Pricing and Features page such that users can directly go to login/signup and contact page from the existing page.  Contact view was having an error an was fixed

**Comment by SayedTabish72** [comment]
## 🙋‍♂️𝗛𝗶 [Sai Aditya Viswanadham](https://github.com/saiadityaviswanadham)
This is [Sayed Tabish](https://github.com/SayedTabish72). I'm participant of **GirlScript Summer Of Code 2022.**  And also I'm Experienced Freelance Web Developer with a demonstrated history of working in the internet industry. Strong engineering professional with a Bachelor of Technology - BTech focused in Information Technology from Dr. A.P.J. Abdul Kalam Technical University. 

👨‍💻And It's very nice to contribute and work for **[CodingEasy](https://github.com/arpit456jain/CodingEasy)** and
 **Modified the Navigation bar in Pricing and features and Fixed the contact view #129** I am interested to work on this issue And also I want to work on such a project that. because I have already worked on similar kind of projects.
![HTML5](https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white) ,   ![CSS3](https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white) , ![JavaScript](https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E)
It will give me a stage to apply my knowledge. building innovative product and put my technical skill to use. plz assign me for the contribution. **I'd love if you assign me for the contribution😊.**

**Comment by arpit456jain** [comment]
hey @SayedTabish72 we have to follow the rule  of first come first serve

**Comment by arpit456jain** [comment]
> The Navigation bar was modified such that users can navigate from Pricing and Features page such that users can directly go to login/signup and contact page from the existing page. Contact view was having an error an was fixed

i am not getting what u want to do first pull the latest changes and then create a new issue and attach some ss for better understanding

**Comment by arpit456jain** [comment]
> ## 🙋‍♂️𝗛𝗶 [Arpit Jain](https://github.com/arpit456jain), [Sai Aditya Viswanadham](https://github.com/saiadityaviswanadham)
> This is [Sayed Tabish](https://github.com/SayedTabish72). I'm participant of **GirlScript Summer Of Code 2022.** And also I'm Experienced Freelance Web Developer with a demonstrated history of working in the internet industry. Strong engineering professional with a Bachelor of Technology - BTech focused in Information Technology from Dr. A.P.J. Abdul Kalam Technical University.
> 
> 👨‍💻And It's very nice to contribute and work for **[CodingEasy](https://github.com/arpit456jain/CodingEasy)** and **Modified the Navigation bar in Pricing and features and Fixed the contact view #129** I am interested to work on this issue And also I want to work on such a project that. because I have already worked on similar kind of projects. ![HTML5](https://camo.githubusercontent.com/49fbb99f92674cc6825349b154b65aaf4064aec465d61e8e1f9fb99da3d922a1/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f68746d6c352d2532334533344632362e7376673f7374796c653d666f722d7468652d6261646765266c6f676f3d68746d6c35266c6f676f436f6c6f723d7768697465) , ![CSS3](https://camo.githubusercontent.com/e6b67b27998fca3bccf4c0ee479fc8f9de09d91f389cccfbe6cb1e29c10cfbd7/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f637373332d2532333135373242362e7376673f7374796c653d666f722d7468652d6261646765266c6f676f3d63737333266c6f676f436f6c6f723d7768697465) , ![JavaScript](https://camo.githubusercontent.com/aeddc848275a1ffce386dc81c04541654ca07b2c43bbb8ad251085c962672aea/68747470733a2f2f696d672e736869656c64732e696f2f62616467652f6a6176617363726970742d2532333332333333302e7376673f7374796c653d666f722d7468652d6261646765266c6f676f3d6a617661736372697074266c6f676f436f6c6f723d253233463744463145) It will give me a stage to apply my knowledge. building innovative product and put my technical skill to use. plz assign me for the contribution. **I'd love if you assign me for the contribution😊.**

@SayedTabish72 create ur own issue if u want to add something
